---
deployment:
  tasks:
    - export DEPLOYPATH=/home/somikoro/ver2
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp bun.lock $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && node dist/server/index.mjs
